### ISSUE TITLE
Unsolvable Puzzle

### ISSUE THREAD

**Issue by bluswimmer** [dm1try/wordle#16]
Recently a friend and I ran into a seemingly unsolvable puzzle.

![don't](https://user-images.githubusercontent.com/12900257/152080405-fc332c7d-6680-43f3-97c7-56e03e5fb34e.png)

We tried every possible combination here and we couldn't solve it. My friend speculates that whatever dictionary you're pulling from has "don't" in it, and the apostrophe makes the word impossible.

**Comment by dm1try** [comment]
Yeah, your friend is right. I've checked the dictionary

```ruby
redis.smembers('words_en').each do |word|
  puts "#{word} is wrong" unless word.match(/^[a-z]+$/)
end
```
```
2,500 is wrong
long, is wrong
don't is wrong
3,000 is wrong
```
 
Sorry for that :) fixed . I'll add a better validation for the parser script.
Thanks!
